[package]
name = "merkle-poseidon"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
opt-level = 's'

[features]
default = []
visualize = []

[dependencies]
ark-bn254 = "0.5.0"
ark-ff = "0.5.0"
light-poseidon = "0.3.0"
thiserror = "2.0.11"
